# Generated by Django 5.1 on 2024-08-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
    ]
