# Generated by Django 5.1 on 2024-09-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_module', '0002_alter_collection_options_collection_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='is_active',
        ),
    ]
