# Generated by Django 4.2 on 2024-08-16 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post_module', '0004_remove_linkbox_post_delete_link_delete_linkbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان باکس')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_module.post', verbose_name='پست')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='لینک')),
                ('link', models.URLField(verbose_name='لینک')),
                ('link_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_links.linkbox', verbose_name='جزو باکس')),
            ],
        ),
    ]
