# Generated by Django 5.1 on 2024-08-21 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_links', '0003_alter_link_options_alter_link_title'),
        ('post_module', '0012_rename_video_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان باکس لینک')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_module.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'باکس لینک',
                'verbose_name_plural': 'باکس\u200cهای دانلود',
            },
        ),
    ]
