# Generated by Django 5.1 on 2024-08-24 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_links', '0005_link_link_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_links', to='post_links.linkbox', verbose_name='باکس لینک'),
        ),
    ]
