# Generated by Django 5.1 on 2024-09-02 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_links', '0006_alter_link_link_box'),
        ('post_module', '0025_alter_postcomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='post_links.linkbox', verbose_name='باکس لینک'),
        ),
        migrations.AlterField(
            model_name='linkbox',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_box', to='post_module.post', verbose_name='پست'),
        ),
    ]
