# Generated by Django 4.2 on 2024-08-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_remove_link_link_box_link_post_delete_linkbox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'لینک', 'verbose_name_plural': 'لینک\u200cها'},
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان لینک'),
        ),
    ]
