# Generated by Django 5.1 on 2024-08-21 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_linkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link_box',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='links.linkbox', verbose_name='باکس لینک'),
            preserve_default=False,
        ),
    ]
