# Generated by Django 5.1 on 2024-08-28 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post_module', '0019_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فایل')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/post', verbose_name='فایل')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_module.post')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل\u200cها',
            },
        ),
    ]
