# Generated by Django 4.2 on 2024-08-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='featured_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='post_module.post', verbose_name='پست\u200cهای دسته\u200cبندی'),
        ),
    ]
