# Generated by Django 4.2 on 2024-08-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0002_remove_post_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
