# Generated by Django 4.2 on 2024-08-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0002_alter_collection_featured_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان باکس')),
            ],
        ),
        migrations.AlterModelOptions(
            name='link',
            options={},
        ),
        migrations.RemoveField(
            model_name='link',
            name='post',
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=255, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='post',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='post_module.collection', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='متن کوتاه'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='linkbox',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_module.post', verbose_name='پست'),
        ),
        migrations.AddField(
            model_name='link',
            name='link_box',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='post_module.linkbox', verbose_name='جزو باکس'),
            preserve_default=False,
        ),
    ]
