# Generated by Django 4.2 on 2024-08-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0003_linkbox_alter_link_options_remove_link_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkbox',
            name='post',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='LinkBox',
        ),
    ]
