# Generated by Django 5.1 on 2024-08-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0005_alter_collection_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'فایل', 'verbose_name_plural': 'فایل\u200cها'},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/post', verbose_name='تصویر پست'),
        ),
    ]
