# Generated by Django 5.1 on 2024-08-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0006_alter_file_options_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/post', verbose_name='تصویر پست'),
        ),
    ]
