# Generated by Django 5.1 on 2024-08-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0008_alter_post_collection_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='featured_post',
            new_name='post',
        ),
    ]
