# Generated by Django 5.1 on 2024-08-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0009_rename_featured_post_collection_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='video',
        ),
    ]
