# Generated by Django 5.1 on 2024-08-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0010_rename_file_file_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default=None, max_length=255, verbose_name='عنوان فایل'),
            preserve_default=False,
        ),
    ]
