# Generated by Django 5.1 on 2024-08-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0011_file_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='video',
            new_name='file',
        ),
    ]
