# Generated by Django 5.1 on 2024-08-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0012_rename_video_file_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='last_update',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
