# Generated by Django 5.1 on 2024-08-26 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0014_remove_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='is_recommend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_module.collection', verbose_name='ابردسته\u200cبندی'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='collection',
        ),
        migrations.AddField(
            model_name='post',
            name='collection',
            field=models.ManyToManyField(related_name='posts', to='post_module.collection', verbose_name='دسته\u200cبندی'),
        ),
    ]
