# Generated by Django 5.1 on 2024-08-26 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0015_remove_collection_post_post_is_recommend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='collection',
        ),
        migrations.AddField(
            model_name='post',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post_module.collection', verbose_name='دسته\u200cبندی'),
        ),
    ]
