# Generated by Django 5.1 on 2024-08-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0016_remove_post_collection_post_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
