# Generated by Django 5.1 on 2024-08-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0017_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('Disable', 0), ('Active', 1), ('Pending', 2)], default=1),
        ),
    ]
