# Generated by Django 5.1 on 2024-08-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0018_alter_post_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
