# Generated by Django 5.1 on 2024-08-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0021_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('Disable', 0), ('Active', 1), ('Pending', 2)], default=2),
        ),
    ]
