# Generated by Django 5.1 on 2024-08-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0023_alter_post_created_at_alter_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Disable'), (1, 'Active'), (2, 'Pending')], default=2),
        ),
    ]
