# Generated by Django 5.1 on 2024-09-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0026_alter_post_options_alter_post_collection_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
